spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hospital
    username: postgres
    password: 456784

  jpa:
    hibernate:
      ddl-auto: create-drop


server:
  servlet:
    context-path: /api/v1


